### ISSUE TITLE
decodeURI causes server error when uri malformed.

### ISSUE THREAD

**Issue by jordanramstad** [nuxt-community/redirect-module#11]
While causing an error itself is fine, but there should be some way to catch the error and possibly do a redirect rather then stopping the execution of the app (this mainly applies to malformed links to the app).

Having it throw an exception as it does is fine by default, but there should be some sort of event that can be used to force a redirect. Likely just from a try/catch on the `decodeURI` function.

Like so (in `nuxt.config.js`): 
```
redirectError(url, error) {
   return '/?err_info=' + error.code //could pass some info if possible
}
```

Though I would think it would be better to keep everything under "redirect" but that would likely lead to a breaking change.

Could add info for things like status code and all that in the return, handling even times when the url might be repairable, just not by `decodeURI`.

This case mainly comes up from migrating to nuxt from a pre-established site where there might be bad url's that need to be handled for a time. In the case here, there are 90k pages in the site migrated and this error has been triggered about once a day since launch, it is also seen in Google Search Console so google reads them as valid links on its end but can't track down the locations of all the links easily. It would be easier to cache the error and redirect that way in my mind.

I plan to eventually do a pull request when I get time, it does not seem like it would be a terribly difficult update to do (and it would get sentry to stop yelling at me lol). Would this be a good way of handling this? Or would there be a better method?

**Comment by manniL** [comment]
Hey! Thanks for the issue ☺️ 

Sounds like a good use case 👍 

To implement that feature I'd change the key structure (while maintaining the old one to not cause breaking changes).

Old (direct array):

```js
{
  redirect: [ { /* rule 1 */ }, { /* rule 2 */ } ]
}
```

New (object with rules + error)
```js
{
  redirect: {
    rules: [ { /* rule 1 */ }, { /* rule 2 */ } ],
    onDecodeError(){ /* error fn here */}
  }
}
```

related lines where the fn could be implemented: https://github.com/nuxt-community/redirect-module/blob/master/lib/middleware.js#L6

With the new style we can leave the door open for further keys/options ☺️ 

I'd be happy if you'd submit a PR but if you don't have time, please ping me and I guess I'd find some time in the next weeks.

**Comment by jordanramstad** [comment]
Should be able to fine some time later this month @manniL and I will try to get a PR together then.

**Comment by jordanramstad** [comment]
@manniL 

I have done some work to adjust add the feature, however when doing it in the project I am working on I found I also needed to add the ability to handle 410 status codes and ended up rewriting most of it into a more or less "new" version, so the code I used can't really be applied into the main repository.

Also I found to make it work the way discussed, I had to refactor a great deal of the code. However I do feel there might be a cleaner way to achieve it that I am just not thinking of.

But here is some bits of it that can be applied to the main repo, though I am unsure the changes that might be required to the tests.

To allow backwards compatibility I did this in the `module.js` file so that `redirect` could take a function, an object or an array and handle it accordingly (adjusted from my changed code, might not work as written).

```
//Backwards compatibility for options to either be an array of rules or an object
const options = {
    rules: []
}
if (typeof this.options.redirect === 'object') {
    if (typeof this.options.redirect.rules === 'function') {
        options.rules = await this.options.redirect.rules()
    }
    if (typeof this.options.redirect.onDecodeError === 'function') {
        options.onDecodeError = this.options.redirect.onDecodeError
    }
} else {
    if (typeof this.options.redirect === 'function') {
        options.rules = await this.options.redirect()
    }
    if (Array.isArray(this.options.redirect)) {
        options.rules = this.options.redirect
    }
}

if (!options.onDecodeError) {
    options.onDecodeError = () => {
        throw new Error('Could not decode uri')
    }
}
```
I feel that was fairly messy so I am open to any better methods to do so, it was fairly rushed. With this instead of the `regExpRules` the new `options` object is passed to the middleware, and the rules are replaced with the regExpRules before for being passed to it.

After that for `middleware.js` I just weapped the `decodeUri` with try/catch and ran `onDecodeError` if it failed, using the rules from the `options` object instead of the old `regExpRules` parameter. 

If you feel this is good I can apply it to a PR for you to look at a bit better, but I won't be able to extensively test anytime soon it which is why I am making this comment. If you feel it worthwhile I can open another issue explaining the use of adding in 410 support and if so I could use the entire codebase I adjusted in a PR, but it extends this module from just being "redirects" into being a more complete status handler.

**Comment by alanaasmaa** [comment]
Hi,

Could you give me a direction how could I debug the cause on production?
I have no idea what pages cause this error.

Regards.

**Comment by ricardogobbosouza** [comment]
I'm working on this feature...

**Comment by ricardogobbosouza** [comment]
@jordanramstad 
See what you think #35 :smile:
