### ISSUE TITLE
Allow host configuration, so we can perform non-www to www redirects

### ISSUE THREAD

**Issue by abishekrsrikaanth** [nuxt-community/redirect-module#12]
I was looking at this module initially to see if this can be used to redirect `non-www` traffic to `www` traffic. Since the redirects are based on URL's I had to look for alternatives, but if there was a way to do this using this module, that would be great.

**Comment by manniL** [comment]
I've marked it as feature request but I think a dedicated package/module/middleware would be better suited 🤔

**Comment by ricardogobbosouza** [comment]
Use https://github.com/nuxt-community/redirect-ssl for example

**Comment by ricardogobbosouza** [comment]
I don't think it belongs to this module, this question

**Comment by warrebuysse** [comment]
@ricardogobbosouza I don't see how redirect-ssl supports non-www to www redirects. Could you elaborate? I have the same question as @abishekrsrikaanth originally asked.

**Comment by ricardogobbosouza** [comment]
@warrebuysse try this:

```js
// nuxt.config.js
const ssl = require('redirect-ssl');

export default {
    serverMiddleware: [
        { handle: ssl.create({ redirectHost: 'www.google.com' }) }
    ]
}
```

See https://github.com/nuxt-community/redirect-ssl#redirect

**Comment by abodity** [comment]
I used this rule, but it doesn't work
`    {
      // Redirect from www to non-www
      // eslint-disable-next-line
      from: '(^http(s?):\/\/?(www\.))(.*)',
      to: (from, req) => {
        // eslint-disable-next-line
        const base = req._parsedUrl.replace(/www\./, '')
        const search = req._parsedUrl.search
        return base + (search != null ? search : '')
      }
    },`

**Comment by abodity** [comment]
> @warrebuysse попробуйте это:
> 
> ```js
> // nuxt.config.js 
> const  ssl  =  require ( 'redirect-ssl' ) 
> const  host  =  'www.google.com'  
> 
> экспорт по  умолчанию  { 
>     serverMiddleware : [ 
>         {  handle : ssl . создать ( {  redirectHost : host  } )  } 
>     ] 
> }
> ```
> 
> См. [Https://github.com/nuxt-community/redirect-ssl#redirect](https://github.com/nuxt-community/redirect-ssl#redirect)

Это тоже не сработало
