### ISSUE TITLE
When in buildModules, redirect does not work

### ISSUE THREAD

**Issue by nickelnext** [nuxt-community/redirect-module#123]
Do you plan on making `redirect-module` compatible with `buildModules `in `nuxt.config.js`?

If put in that part of the config file, the redirect module does not work.

Although in production, when building with `nuxt build --standalone`, it would be better to have the module working from `buildModules`.

Can you make this happen?

Thanks

**Comment by manniL** [comment]
For Nuxt 2, this is not possible because the redirects are triggered on runtime and cannot be "calculated" beforehand 🙈
