### ISSUE TITLE
0.2.0 forces nuxt fatal error

### ISSUE THREAD

**Issue by podlebar** [nuxt-community/redirect-module#16]
After updating to 0.2.0 i get this error when running `npm run dev | build | start`:

```
export default async function nuxtRedirect(moduleOptions) {
^^^^^^

SyntaxError: Unexpected token export
    at Object.Module._extensions..js (module.js:646:10)
    at Object.Module._extensions..js (module.js:646:10) ]


✖ Nuxt Fatal Error  
 SyntaxError: Unexpected token export
 ```

**Node Version**: 8.10.0

**Solution 2:***
use Node 10.x.x

A hint in the Docs would be nice :)

**Comment by manniL** [comment]
Hey! 👋 

Will investigate, thank you 👍

**Comment by manniL** [comment]
@podlebar Do you use Nuxt 1 or Nuxt 2?

**Comment by podlebar** [comment]
we use 2.3.4.. but when i opened this issue it was 2.3.2 i think..

**Comment by manniL** [comment]
![no-repro](https://user-images.githubusercontent.com/640208/49285596-c3f64f00-f48f-11e8-8a11-6a492fc54ef4.gif)

Can't reproduce
