### ISSUE TITLE
Force trailing slash

### ISSUE THREAD

**Issue by Jesus82** [nuxt-community/redirect-module#19]
Hi, first of all, thanks a lot for the module.
I'm trying to force a trailing slash in the end of all my urls ( fx: `https://domain/this-is-an-url/ `) and I have been trying adapting .htaccess formulas with no luck. So far I've tried:
`{ from:  '^(.*)[^/]$ ', to: '$1/' }` (doesn't work)
`{ from:  '^(.*)([^/])$ ', to: '/$1$2/' }` (works correctly if the url doesn't have a slash, but when it has, it ads a second slash in the end.

Any help would be appreciated!

**Comment by manniL** [comment]
Try using a function for that ☺️ 

Example for using a function record:


```js
redirect: [
  {
    from: '^/someUrlHere/(.*)$',
    to: (from, req) => {
      const param = req.url.match(/functionAsync\/(.*)$/)[1]
      return `/posts/${param}`
    }
  }
]
```

**Comment by Jesus82** [comment]
Thanks for the hint. Ended up with this, but it leads to an infinite redirect

```
{
    from: '^(.*)$',
    to: (from, req) => {
      let trailingUrl = req.url.endsWith('/') ? req.url : req.url + '/'
      return trailingUrl
    }
}
```
