### ISSUE TITLE
Leverage vue-router alias/redirect

### ISSUE THREAD

**Issue by manniL** [nuxt-community/redirect-module#3]
Currently, the module only works in `universal mode`, because a `server middleware` is used. A possible solution to make the module work in SPA and generate mode would be the `alias/redirect` options in the vue-router.

Related: #1 
[Read more](https://router.vuejs.org/en/essentials/redirect-and-alias.html)

**Comment by juno-yu** [comment]
looked into this a little bit 
- vue router using path-to-regexp that syntaxically/contextually different from js regex , if we don't move to that and take argument as it does it is difficult to keep route working.
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes

Ignoring this, I have made an implementation based on 'addplugin call in module' approach for a simple path that works in both matching merchanism (a redirect from /abc -> /about)
https://codesandbox.io/s/qkxvnmv104

In spa mode the redirection looks working as expecred, including generating the page for '/abc' by adding it into options.generate.routes

In universal generate mode there is _a blocker_, that the redirection logic by server middleware seems not to be considered so '/abc' is unable to be resolved and generated finally (while in dev mode 1)a direct visit to '/abc' 2)clicking a router-link for '/abc' would both work)

**Comment by manniL** [comment]
@juno-yu Thanks for the research!

I'd appreciate having `spa` redirect support in the module.
For generate your are right, the `server middleware` isn't considered at all. Could we apply the idea from the `spa` version there and leverage the spa fallback mechanism of `generate`?

**Comment by TheAlexLichter** [comment]
Closing, as the module will remain in maintenance only.
