### ISSUE TITLE
Redirect fails when destination path contains slash

### ISSUE THREAD

**Issue by Wiejeben** [nuxt-community/redirect-module#33]
When setting something like this `{from: '/from/something', to: '/to/something'},` the server seems to freeze when browsing to `/from/something`. Not sure what is causing this.

`{from: '/from/something', to: '/to'},` works just fine.

**Comment by ricardogobbosouza** [comment]
@Wiejeben 
It works for me, can you share your settings?

**Comment by Wiejeben** [comment]
Alright, it toke some digging but I found my mistake. Unfortunately there was an error inside `template/error.vue`, this for some reason did not show up in the console and somehow prevented the redirect from happening.
