### ISSUE TITLE
Module crashes site

### ISSUE THREAD

**Issue by invisor** [nuxt-community/redirect-module#43]
Hi. Every time when I adding module to module section is crashing my site. I got this error
`Cannot GET /`
Any links from my site return this error. How to fix this? What additional info do you need?

**Comment by bdrtsky** [comment]
Works fine for me. Any specific info about your issue?

**Comment by JesperHonders** [comment]
Hi, i'm dealing with that same problem.

In the server log it prints:

`node_modules/@nuxtjs/redirect-module/lib/module.js:1
  (function (exports, require, module, __filename, __dirname) { export default async function nuxtRedirect(moduleOptions) {
                                                                ^^^^^^
  SyntaxError: Unexpected token export
`

**Comment by manniL** [comment]
@JesperHonders please make sure you are using Nuxt 2 and upwards.

@invisor 	more info is needed, ideally a reproduction repo.
