### ISSUE TITLE
Doesn't work when non-english character is included in URL

### ISSUE THREAD

**Issue by imkimchi** [nuxt-community/redirect-module#5]

**Comment by manniL** [comment]
Hey @imkimchi! Thanks for the report. Will look into it 😊

**Comment by manniL** [comment]
@imkimchi Thanks for the update with additional information. Maybe we can use `encodeURI` directly in the module to work around the problem :relaxed:

**Comment by manniL** [comment]
Fixed with https://github.com/nuxt-community/redirect-module/commit/759e4bf29dd84508ec59ae6f6b91a9a349388af1, new version will be published as soon as CI passes :relaxed:

**Comment by imkimchi** [comment]
nice work buddy
