### ISSUE TITLE
When new release?

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt-community/redirect-module#51]
Hi, 

I would like to to use onDecode and onDecodeError functions. But it seems latest version in npm is 0.2.0.

**Comment by manniL** [comment]
Soon :relaxed:

**Comment by alanaasmaa** [comment]
@manniL I will use currently master branch.

I have issues with ISO data in external service. 
This handles it somehow.

```
    onDecode: (req, res, next) => {
      let url
      try {
        url = decodeURI(req.url)
      } catch (error) {
        // Rethrow error
        if (error.message !== 'URI malformed') {
          throw error
        }
        url = decodeURI(unescape(req.url))
        // Fix url also on Nuxt side
        req.url = url
      }
      return url
    },

```

**Comment by rchl** [comment]
Please consider #52 before releasing. I'd like to switch back my code to use this module instead of my fork.

**Comment by alanaasmaa** [comment]
Weird works on local on devel but not on master `ERROR  options.onDecodeError is not a function`

**Comment by alanaasmaa** [comment]
> Weird works on local on devel but not on master `ERROR options.onDecodeError is not a function`

Nuked node_modules and started working.

**Comment by manniL** [comment]
There we go!
