### ISSUE TITLE
Russian characters problem 

### ISSUE THREAD

**Issue by chz** [nuxt-community/redirect-module#56]
Hi everyone, 
I have problem when redirect from to 

`{ from: '^/catalog/keyword/(.*)$', to: '/keyword/$1',statusCode: 301 }`

Old: /catalog/обувь
New : /keyword/обувь

its not redirecting server error :/

**Comment by chz** [comment]
With english symbols its ok!

**Comment by iljajetsucgi** [comment]
I might have similar problem with scandinavian characrters , even though it does not produce server errors:

with rule { from: '^/documents/(.*)$', to: '[hostname]/documents/$1' },

URL with /documents/Something%C3%A4/Something 
is redirected as /documents/Something?/Something 
And ? in middle of the url is not going to work..

So the encoding goes wrong somehow.
This is visible while running AWS Lambda, but not on local system, so it might have something to do with locale settings?

**Comment by manniL** [comment]
https://github.com/nuxt-community/redirect-module/issues/5

**Comment by derz** [comment]
Hi @manniL. I think this should be fixed with https://github.com/nuxt-community/redirect-module/pull/58 aswell.
