### ISSUE TITLE
Plus sign (+) origin URL give 404 in Nuxt

### ISSUE THREAD

**Issue by snsxn** [nuxt-community/redirect-module#6]
When trying to redirect from:
```
"^/original+url+to+redirect"
```
Appears 404 before redirecting.
Also tried with %2B and %20 and same not found error.
I'm missing something?

**Comment by manniL** [comment]
Hey @snsxn! This module leverages regular expressions. As`+` is a reserved character in RegEx, you have to escape it in your string ☺️

Either go with a RegExp (for example `/^\/a\+b` matches `/a+b`) or a string with double escape (`^/a\\+b`)

**Comment by manniL** [comment]
Will add more examples in the docs and explanation for edge cases soon 😊
