### ISSUE TITLE
unable to map "#"

### ISSUE THREAD

**Issue by Wilson-Lim** [nuxt-community/redirect-module#82]
I wish to use the value in hash to determine my final url 
```
{
        from: "^/handbook#guide$",
        to: (from, req) => {
          return "/myGuidePage";
        }
}

```
How can i make this work? 

when i key in http://localhost/handbook#guide , the redirection doesnt trigger.

**Comment by rchl** [comment]
Browsers don't send the hash part to the server on SSR request. And this module is for SSR requests.

**Comment by Wilson-Lim** [comment]
@rchl Thanks for the fast response
