### ISSUE TITLE
Can not redirect request to another script.

### ISSUE THREAD

**Issue by FranzSkuffka** [nuxt-community/redirect-module#9]
What am I doing wrong?
```js
{from: '^/load.js$', to: 'https://code.jquery.com/jquery-3.3.1.min.js', statusCode: 200}
```

load.js results in a white page while the jquery URL works without issues.

**Comment by manniL** [comment]
Instead of sending a 200 (which won't perform the redirect), send a 302, 301 or 304 :relaxed:

**Comment by FranzSkuffka** [comment]
Okey but I want to redirect internally but send ok anyways? Like a proxy?

**Comment by manniL** [comment]
@FranzSkuffka You can use https://github.com/nuxt-community/proxy-module/ for that :relaxed: (already comes with `axios-module`)
